name: clone
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  animations: ^2.0.11
  app_ui:
    path: packages/app_ui
  bloc: ^9.0.0
  collection: ^1.19.1
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  envied: ^1.1.1
  equatable: ^2.0.7
  firebase_core: ^3.15.2
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: packages/form_fields
  get_it: ^8.1.0
  go_router: ^16.1.0
  google_sign_in: ^7.1.1
  hydrated_bloc: ^10.1.1
  insta_blocks:
    path: packages/insta_blocks
  instagram_blocks_ui:
    path: packages/instagram_blocks_ui
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  posts_repository:
    path: packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  sliver_tools: ^0.2.12
  sprung: ^3.0.1
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  slang_build_runner: ^4.8.0
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
