name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
dependencies:
  app_ui:
    path: ../app_ui
  env:
    path: ../env
  flutter:
    sdk: flutter
  intl: ^0.20.2
  jiffy: ^6.4.3
  logger: ^2.6.1
  powersync: ^1.15.0
