name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.10.0
  freeze: ^1.0.0

  

dependencies:
  app_ui:
    path: ../app_ui
  bloc_concurrency: ^0.3.0
  blurhash: ^1.2.0
  dio: ^5.9.0
  env:
    path: ../env
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  freezed_annotation: ^3.1.0
  http_parser: ^4.1.2
  image_picker_plus:
    path: ../image_picker_plus
  image_size_getter: ^2.4.1
  insta_blocks:
    path: ../insta_blocks
  intl: ^0.20.2
  jiffy: ^6.4.3
  json_annotation: ^4.9.0
  logger: ^2.6.1
  meta: ^1.16.0
  mime: ^2.0.0
  ogp_data_extract: ^0.2.2
  powersync: ^1.15.0
  stream_transform: ^2.1.1
  user_repository:
    path: ../user_repository
  uuid: ^4.5.1
  video_compress: ^3.1.4
