name: env
description: for managing environmental variables
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  envied: ^1.1.1

dev_dependencies:
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
