// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6q2d4LuqngmzH_QfbXPd8PWymjmCtgC4',
    appId: '1:808662564833:web:8b56d53206297bf2219ca0',
    messagingSenderId: '808662564833',
    projectId: 'clone-stg',
    authDomain: 'clone-stg.firebaseapp.com',
    storageBucket: 'clone-stg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHM3r8FHqlNBOdxtzakqwnCBCxazB_j3I',
    appId: '1:808662564833:android:3b8642e075c9c272219ca0',
    messagingSenderId: '808662564833',
    projectId: 'clone-stg',
    storageBucket: 'clone-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSu0-9ftN6UEApud0ReOMboXyyijWAUM',
    appId: '1:808662564833:ios:8b46d1d4ac58c9ac219ca0',
    messagingSenderId: '808662564833',
    projectId: 'clone-stg',
    storageBucket: 'clone-stg.firebasestorage.app',
    iosClientId: '808662564833-bj7fe9sa2dovrnd7ob4m58p3n9j13kc1.apps.googleusercontent.com',
    iosBundleId: 'com.cloney1.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUSu0-9ftN6UEApud0ReOMboXyyijWAUM',
    appId: '1:808662564833:ios:c9eea98b72d7cb7e219ca0',
    messagingSenderId: '808662564833',
    projectId: 'clone-stg',
    storageBucket: 'clone-stg.firebasestorage.app',
    iosClientId: '808662564833-phgi3i77in16cqkpfjhpug8pjlt8osus.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6q2d4LuqngmzH_QfbXPd8PWymjmCtgC4',
    appId: '1:808662564833:web:2502e68505cdce38219ca0',
    messagingSenderId: '808662564833',
    projectId: 'clone-stg',
    authDomain: 'clone-stg.firebaseapp.com',
    storageBucket: 'clone-stg.firebasestorage.app',
  );
}
