// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlAi9hAwOTMgXJG72JbiJQV7Ucz2Ul87A',
    appId: '1:964527279157:web:d7751098699a5a06a7f57c',
    messagingSenderId: '964527279157',
    projectId: 'clone-dev-7da5f',
    authDomain: 'clone-dev-7da5f.firebaseapp.com',
    storageBucket: 'clone-dev-7da5f.firebasestorage.app',
    measurementId: 'G-DG38V9998Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsBlEJ1v_ETLhy6M5cOaYNXpR7C8zMoGw',
    appId: '1:964527279157:android:fd7d1fb3d66145b5a7f57c',
    messagingSenderId: '964527279157',
    projectId: 'clone-dev-7da5f',
    storageBucket: 'clone-dev-7da5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR8VgRCZyLJh4-8Sf7Vijhv2dPVrYmL78',
    appId: '1:964527279157:ios:f0173b32db913fdfa7f57c',
    messagingSenderId: '964527279157',
    projectId: 'clone-dev-7da5f',
    storageBucket: 'clone-dev-7da5f.firebasestorage.app',
    iosClientId: '964527279157-s9is7qmhj0ba2lq2tia1d39nd3qgtprq.apps.googleusercontent.com',
    iosBundleId: 'com.cloney1.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR8VgRCZyLJh4-8Sf7Vijhv2dPVrYmL78',
    appId: '1:964527279157:ios:12527cbd5358a74ba7f57c',
    messagingSenderId: '964527279157',
    projectId: 'clone-dev-7da5f',
    storageBucket: 'clone-dev-7da5f.firebasestorage.app',
    iosClientId: '964527279157-6csrl9jihqnpnng67atki23bp01n3c0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlAi9hAwOTMgXJG72JbiJQV7Ucz2Ul87A',
    appId: '1:964527279157:web:a359218cf5598734a7f57c',
    messagingSenderId: '964527279157',
    projectId: 'clone-dev-7da5f',
    authDomain: 'clone-dev-7da5f.firebaseapp.com',
    storageBucket: 'clone-dev-7da5f.firebasestorage.app',
    measurementId: 'G-8CY8M2P7G2',
  );
}
