// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMgBUvOKHlmbQrSM8_e90d81_ArEpyDo',
    appId: '1:431588914468:web:9ddcf5260ec14634bf6fb1',
    messagingSenderId: '431588914468',
    projectId: 'clone-prod-67ce4',
    authDomain: 'clone-prod-67ce4.firebaseapp.com',
    storageBucket: 'clone-prod-67ce4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc4AtY7Azoi9__daidhxTMAaToyAOcr6k',
    appId: '1:431588914468:android:d6405a23e10d2563bf6fb1',
    messagingSenderId: '431588914468',
    projectId: 'clone-prod-67ce4',
    storageBucket: 'clone-prod-67ce4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaGfS_PMtXn_tCEkBEIqcV3aMgrGdeizM',
    appId: '1:431588914468:ios:1b7c379e1950ea9cbf6fb1',
    messagingSenderId: '431588914468',
    projectId: 'clone-prod-67ce4',
    storageBucket: 'clone-prod-67ce4.firebasestorage.app',
    iosClientId: '431588914468-pubofhe2lcbgel6r6p39m98coj0nhnoh.apps.googleusercontent.com',
    iosBundleId: 'com.cloney1.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaGfS_PMtXn_tCEkBEIqcV3aMgrGdeizM',
    appId: '1:431588914468:ios:a22ad26ac9ee7f5ebf6fb1',
    messagingSenderId: '431588914468',
    projectId: 'clone-prod-67ce4',
    storageBucket: 'clone-prod-67ce4.firebasestorage.app',
    iosClientId: '431588914468-1eo2fn4f84if9kllhtd6t3kkl8d7p568.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPMgBUvOKHlmbQrSM8_e90d81_ArEpyDo',
    appId: '1:431588914468:web:6bb0a8899791f03cbf6fb1',
    messagingSenderId: '431588914468',
    projectId: 'clone-prod-67ce4',
    authDomain: 'clone-prod-67ce4.firebaseapp.com',
    storageBucket: 'clone-prod-67ce4.firebasestorage.app',
  );
}
