name: powersync_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
 shared:
    path: ../shared

 env:
    path: ../env

 flutter:
    sdk: flutter
 path: ^1.9.1  
 powersync: ^1.15.0
 supabase_flutter: ^2.9.1
 path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
